name = "arena-play"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "arena-play-leads"
database_id = "4e970da3-0c43-4c3f-be79-fd792f2e196f"

[env.production]
name = "arena-play"

[[env.production.d1_databases]]
binding = "DB"
database_name = "arena-play-leads"
database_id = "4e970da3-0c43-4c3f-be79-fd792f2e196f"
